---
chances:
  COAL:
    fortune-0:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.06
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.07
      max-amount: 4
      min-amount: 3
  DIAMOND:
    fortune-0:
      chance: 0.005
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.005
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.006
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.007
      max-amount: 4
      min-amount: 3

  EMERALD:
    fortune-0:
      chance: 0.01
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.01
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.02
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.03
      max-amount: 4
      min-amount: 3
  GOLD_INGOT:
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.02
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.03
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.04
      max-amount: 4
      min-amount: 3
  IRON_INGOT:
    fortune-0:
      chance: 0.03
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.03
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.04
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.05
      max-amount: 4
      min-amount: 3
  LAPIS_LAZULI:
    fortine-2:
      chance: 0.02
      max-amount: 5
      min-amount: 4
    fortune-0:
      chance: 0.01
      max-amount: 3
      min-amount: 2
    fortune-1:
      chance: 0.02
      max-amount: 4
      min-amount: 3
    fortune-3:
      chance: 0.03
      max-amount: 6
      min-amount: 5
  REDSTONE:
    fortune-0:
      chance: 0.02
      max-amount: 3
      min-amount: 2
    fortune-1:
      chance: 0.03
      max-amount: 4
      min-amount: 3
    fortune-2:
      chance: 0.04
      max-amount: 5
      min-amount: 4
    fortune-3:
      chance: 0.05
      max-amount: 6
      min-amount: 5

chest-spawn-chance: 1.0
chest:
  DIAMOND:
    chance: 0.8
    min: 1
    max: 10
  ENCHANTED_GOLDEN_APPLE:
    chance: 0.2
    min: 1
    max: 1
  SADDLE:
    chance: 0.6
    min: 1
    max: 1
  GOLDEN_CARROT:
    chance: 1.0
    min: 5
    max: 40
  WITHER_SKELETON_SKULL:
    chance: 0.04
    min: 1
    max: 1
  GHAST_TEAR:
    chance: 0.1
    min: 2
    max: 5
  STONE:
    chance: 1.0
    min: 1
    max: 64
  DIAMOND_SWORD:
    chance: 1.0
    min: 1
    max: 1
    enchant: smite
    level: 3
users: ~
