name: DropPlugin
description:
api-version: 1.13
version: 1.0
main: me.apisek12.plugin.PluginMain
commands:
  shutdown:
  drop:
    description: Modyfikuj ustawienia dropu.
    aliases: [d]
  codropi:
    description: Pokazuje szansze na drop
  emergencyDisable:
    description: Wylacz awaryjnie plugin
  cancelShutdown:
    description: Anuluj komende /shutdown
